jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "chocolateen"
          name: "Hugo"
          password: "${USER_CHOCOLATEEN_PASSWORD}"
        - id: "vaugie_g"
          name: "Garance"
          password: "${USER_VAUGIE_G_PASSWORD}"
        - id: "i_dont_know"
          name: "Jeremy"
          password: "${USER_I_DONT_KNOW_PASSWORD}"
        - id: "nasso"
          name: "Nassim"
          password: "${USER_NASSO_PASSWORD}"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            entries:
              - user: "chocolateen"
            permissions:
              - "Overall/Administer"
          - name: "ape"
            description: "Pedagogical team member"
            entries:
              - user: "i_dont_know"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Build"
              - "Job/Workspace"
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            entries:
              - user: "vaugie_g"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Build"
              - "Job/Workspace"
              - "Job/Cancel"
              - "Job/Configure"
              - "Job/Create"
              - "Job/Delete"
              - "Job/Move"
          - name: "assist"
            description: "Assistant"
            entries:
              - user: "nasso"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Workspace"

jobs:
  - file: /var/jenkins_home/job_dsl.groovy

security:
  scriptApproval:
    approvedScriptHashes:
      - "SHA512:93af3bc8dd3d2d4e1d84c39388e8d94688d3bc894cdc70659fdda6315e3ed78a8e11b6a7202386fb287108e13e154344c79d9b23db08934a4777e78c7f8249c0"
